In [2]:
# used for traditional ml
from skimage.io import imshow
from skimage.transform import resize
from skimage.feature import hog
from skimage import exposure
import matplotlib.pyplot as plt
import cv2

def getHOG(img):
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    resized_img = resize(gray, (224, 224))
    # resized_img /= 255.0
    # imshow(resized_img)
    fd, hog_image = hog(resized_img, orientations=9, pixels_per_cell=(8, 8), 
                    cells_per_block=(2, 2), visualize=True, block_norm="L2")
    return fd, hog_image

def getSIFT(img):
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    resized_img = resize(gray, (64, 64))
    resized_img = cv2.normalize(resized_img, None, 0, 255, cv2.NORM_MINMAX).astype("uint8")
    sift = cv2.SIFT_create()
    _, des = sift.detectAndCompute(resized_img, None)
    return des

def getORB(img):
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    resized_img = resize(gray, (224, 224))
    resized_img = cv2.normalize(resized_img, None, 0, 255, cv2.NORM_MINMAX).astype("uint8")
    orb = cv2.ORB_create()
    _, des = orb.detectAndCompute(resized_img, None)
    return des

# print("!")
img = cv2.imread("images/200.jpg")
print(img.shape)
fd, h = getHOG(img)
print(fd.shape)

(224, 224, 3)
(26244,)


In [9]:
from sklearn.model_selection  import cross_val_score
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score

from sklearn.datasets import load_iris
import feature_extraction
from utils import *
import numpy as np

KF = KFold(n_splits=5)
X = [[1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4], [5, 5, 5]]

for train_index, test_index in KF.split(X):
    # print(train_index)
    X_train = np.array(X)[train_index]
    print(X_train)


[[2 2 2]
 [3 3 3]
 [4 4 4]
 [5 5 5]]
[[1 1 1]
 [3 3 3]
 [4 4 4]
 [5 5 5]]
[[1 1 1]
 [2 2 2]
 [4 4 4]
 [5 5 5]]
[[1 1 1]
 [2 2 2]
 [3 3 3]
 [5 5 5]]
[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]
